AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Prediction 
Resources:
  LambdaChecker:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdachecker.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 3
      CodeUri: 'https://github.com/diegonat/smsantispam/raw/master/lambdachecker.js.zip'