AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Prediction 
Resources:
  SMSantispam:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python2.7
      MemorySize: 1024
      Timeout: 10
      CodeUri: ./
      Events:
        SMSspam:
          Type: Api
          Properties:
            Path: /
            Method: GET
